In [66]:
import numpy as np
from sklearn.datasets import load_boston
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from tqdm import tqdm

In [3]:
boston = load_boston()
x=boston.data #independent variables
y=boston.target #target variable

In [5]:
print(len(x))
print(len(y))

506
506


In [51]:
x

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [30]:
#Step-1
#creating 30 samples from the whole boston data points.
col=np.arange(13)
x_num=np.arange(len(x))
y_num=np.arange(len(y))
col_set=[]
X_train=[]
X_test=[]
Y_train=[]
Y_test=[]
col_train_set=[]
for i in range(30):
    #randomly choosing different feature for each sample
    col_train, col_ignore= train_test_split(col, test_size=0.50,random_state=2*i)
    col_train=np.sort(col_train)
    col_train_set.append(col_train)
    #X=x[:,col_train]
    X_tr0, X_te0, y_tr0, y_te0 = train_test_split(x_num, y_num, test_size=0.40,random_state=3*i) #60% of x data
    X_tr1, X_te1, y_tr1, y_te1 = train_test_split(X_tr0, y_tr0, test_size=0.33,random_state=2*i) #taking 40%of data from x_train(60% of x)
    #addiing up the 60% and 40% values
    X_tr_final=np.hstack((X_tr0,X_tr1))
    y_tr_final=np.hstack((y_tr0,y_tr1))
    #Corpus of 30 samples
    X_train.append(X_tr_final)
    X_test.append(X_te0)
    Y_train.append(y_tr_final)
    Y_test.append(y_te0)

In [36]:
X_train[0]

array([198, 145, 158, 150, 250, 485, 167,  85, 236, 436,  66, 312, 429,
       140, 101, 393,   2, 413, 221,  17, 146, 255, 357,  30, 114, 238,
       103, 456, 313, 176, 252, 116, 168, 441, 120, 264, 112, 364, 347,
       463, 136, 190, 351, 181, 126, 284,  34, 412, 377, 424, 232, 133,
        33, 482,  44,  61, 199, 271, 289, 218,  73,  35, 444,  29, 365,
       345, 457, 217,  27, 467, 295, 156, 339, 382, 138, 212, 104, 354,
       350, 355, 215, 439, 189, 214, 204, 234, 259,  67,  24, 216, 223,
       129, 111, 166, 422, 399,  40, 274, 361,  79, 316, 318,  13, 287,
       414, 500, 228, 161,  83, 503, 479, 110, 149, 152,  16, 343, 109,
       406, 139, 237, 260, 362, 317, 501, 405, 248, 332, 390,  19, 328,
       296, 269, 226, 434,   3, 353, 125, 280, 286,  77, 184, 380, 483,
       275, 294, 442, 182, 453,  80, 307, 258,  11, 375,  86, 266,  36,
       486,  58,  41, 270,  50, 209, 402, 401, 421, 123, 222,  62, 381,
       130, 187,  23,  43, 447,   0, 201, 368, 432,  98, 349, 30

In [33]:
#Step-2
from sklearn.tree import DecisionTreeRegressor
clf=DecisionTreeRegressor()
y_train_pred=[]
y_test_pred=[]
y_pred=[]
y_pred_test=[]
#y_pred corpus
for i in range(30):
    y_total_pred=[]
    clf.fit(x[:,col_train_set[i]][X_train[i]], y[Y_train[i]])
    y_pred.append(clf.predict(x[:,col_train_set[i]]))
    y_pred_test.append(clf.predict(x[:,col_train_set[i]][X_test[i]]))
#computing Average y_pre value    
y_sum=y_pred[0]
for j in range(len(y_pred)):
    y_sum=+np.add(y_sum,y_pred[j])
y_pred_avg=np.true_divide(y_sum, 30)
#computing MSE:
y_mse=np.subtract(y,y_pred_avg)#y-y_pred
y_mse_sqr=np.square(y_mse)#squaring the diff
y_mse_final=np.true_divide(y_mse_sqr, 506)
print(len(y_mse_final))

506


In [94]:
#Step-3:
y_pred_oob=[]
countp=[]

X_trains=np.asarray(X_train)
for i in range(len(x)):
    count=0
    sum1=0
    for j in range(30): 
        if i in X_test[j]:
            #print(i,j)
            count=count+1
            #print(count)
            clf.fit(x[:,col_train_set[j]][X_train[j]], y[Y_train[j]])
            sum1=sum1+clf.predict((x[:,col_train_set[0]][0].reshape(1,-1)))
    y_pred_oob.append(sum1/count) 
    
#computing OOB SCORE:
y_oob=np.subtract(y,y_pred_oob)#y-y_pred_oob
y_oob_sqr=np.square(y_mse)#squaring the diff
y_oob_final=np.true_divide(y_mse_sqr, 506)
print(len(y_oob_final))    

506


In [93]:
y_pred_tft

[array([27.85]),
 array([25.63636364]),
 array([21.51818182]),
 array([26.56153846]),
 array([23.8]),
 array([27.47857143]),
 array([26.18125]),
 array([26.83076923]),
 array([25.86923077]),
 array([23.27857143]),
 array([24.87692308]),
 array([25.48461538]),
 array([27.07857143]),
 array([25.78333333]),
 array([27.06666667]),
 array([24.46666667]),
 array([26.675]),
 array([25.48181818]),
 array([24.05625]),
 array([23.51]),
 array([24.12]),
 array([26.59333333]),
 array([27.42]),
 array([25.09230769]),
 array([26.21666667]),
 array([23.99285714]),
 array([27.93125]),
 array([27.13]),
 array([23.26666667]),
 array([26.71111111]),
 array([22.7]),
 array([25.32727273]),
 array([24.16]),
 array([22.5]),
 array([24.75]),
 array([29.28181818]),
 array([24.05]),
 array([26.88125]),
 array([24.72]),
 array([25.22777778]),
 array([27.58333333]),
 array([26.72222222]),
 array([27.625]),
 array([27.49]),
 array([24.7]),
 array([23.86428571]),
 array([25.55]),
 array([27.11818182]),
 array([27.7

In [86]:
countp

[14,
 11,
 11,
 13,
 12,
 14,
 16,
 13,
 13,
 14,
 13,
 13,
 14,
 12,
 12,
 12,
 12,
 11,
 16,
 10,
 15,
 15,
 10,
 13,
 12,
 14,
 16,
 10,
 9,
 9,
 11,
 11,
 10,
 10,
 8,
 11,
 4,
 16,
 15,
 18,
 12,
 9,
 12,
 10,
 19,
 14,
 12,
 11,
 10,
 8,
 13,
 13,
 14,
 9,
 8,
 14,
 14,
 11,
 7,
 13,
 10,
 14,
 12,
 11,
 11,
 14,
 11,
 16,
 17,
 16,
 13,
 13,
 13,
 10,
 12,
 8,
 16,
 10,
 12,
 11,
 10,
 10,
 11,
 7,
 13,
 9,
 9,
 13,
 11,
 14,
 13,
 10,
 12,
 12,
 10,
 12,
 14,
 10,
 14,
 10,
 14,
 12,
 5,
 15,
 12,
 12,
 14,
 6,
 14,
 10,
 12,
 12,
 13,
 9,
 10,
 11,
 13,
 14,
 14,
 12,
 8,
 8,
 13,
 12,
 13,
 14,
 19,
 11,
 12,
 9,
 10,
 12,
 16,
 7,
 16,
 16,
 15,
 13,
 14,
 12,
 15,
 12,
 12,
 12,
 13,
 8,
 14,
 20,
 15,
 10,
 10,
 9,
 13,
 12,
 14,
 15,
 12,
 17,
 9,
 16,
 11,
 10,
 10,
 9,
 13,
 13,
 12,
 10,
 10,
 12,
 10,
 12,
 13,
 9,
 7,
 15,
 8,
 14,
 11,
 16,
 16,
 11,
 11,
 11,
 10,
 11,
 12,
 9,
 19,
 13,
 11,
 13,
 12,
 14,
 15,
 14,
 12,
 16,
 9,
 11,
 16,
 15,
 10,
 13,
 12,
 9,
